import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Amine Portfolio</title>
        <meta name="description" content="Generated by Amine-Next-JS" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Amine Portfolio
        </h1>

        <div className={styles.grid}>

          <a href="https://www.linkedin.com/in/amine-amine-885137153" className={styles.card}>
            <h2>Linked In &rarr;</h2>
            <p>Check my work Experience in full stack development.</p>
          </a>

          <a
            href="https://github.com/aminects"
            className={styles.card}
          >
            <h2>Github &rarr;</h2>
            <p>CHeck my projects and applications.</p>
          </a>

          <a href="https://www.instagram.com/aminee.a/" className={styles.card}>
            <h2>Instagram &rarr;</h2>
            <p>Check my posts and stories.</p>
          </a>

          <a
            href="https://www.facebook.com/people/Amine-Amine/100022631154224/?viewas=100000686899395"
            className={styles.card}
          >
            <h2>Facebook &rarr;</h2>
            <p>
              CHeck my facebook page.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/aminects"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>Amine-Next-JS</span>
        </a>
      </footer>
    </div>
  )
}
